import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "features/header/Header";
import Footer from "features/footer/Footer";
import { SessionProvider } from "next-auth/react"
import { type Session } from "next-auth";
import Loading from "components/Loading";
import UserSessionProvider from "providers/UserSessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children}: Readonly<{
  children: React.ReactNode
}>) {

  
  return (
    <html lang="en" data-theme="emerald">
      <body className={inter.className}>
      <UserSessionProvider >
        <Header />
        <Loading />
        <main className="container mx-auto pt-20 min-h-screen">{children}</main>
        <Footer />
        </UserSessionProvider>
      </body>
    </html>
  );
}
