import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "features/header/Header";
import Footer from "features/footer/Footer";
import { SessionProvider } from "next-auth/react"
import { type Session } from "next-auth";
import Loading from "components/Loading";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session}: Readonly<{
  children: React.ReactNode,
  session: Session | null;
}>) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProvider session={session}>
        <Header />
        <Loading />
        <main className="container mx-auto pt-20 min-h-screen">{children}</main>
        <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
